### ISSUE TITLE
tls support?

### ISSUE THREAD

**Issue by SEJeff** [gyselroth/kube-ldap#1]
TLS is preferable for anything that handles user credentials.

**Comment by juckerf** [comment]
Hi Jeff,
Thanks for pointing this out. In our setup the TLS connection is terminated before kube-ldap, that's probably why this essential feature was not implemented when open sourcing the project.
But you're right, no doubt, we should implement TLS as secure default.
I will instantly update the README to advise users to use some kind of TLS reverse proxy (like nginx) in front of kube-ldap and start implementing TLS support.

**Comment by juckerf** [comment]
I added tls (https) support and released kube-ldap version 1.1.0 (including docker image)
